#!/bin/bash

source "vars"
INPUT_URL="https://adventofcode.com/${YEAR}/day/$((10#${DAY}))/input"

cp "main.nim" "nim/day${DAY}.nim"
cp "main.ml" "ocaml/day${DAY}.ml"
curl $INPUT_URL --cookie "session=${TOKEN}" > "input/day${DAY}.txt"

subl -a "input/day${DAY}.txt"
subl -a "nim/day${DAY}.nim"
xdg-open "https://adventofcode.com/${YEAR}/day/$((10#${DAY}))"
